version: '3'

services:
  glance:
    image: ghcr.io/noahgaertner/glance:latest
    container_name: glance
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./glance.yml:/app/config/glance.yml:ro
      - ./data:/app/data
    environment:
      - TZ=America/Los_Angeles

volumes:
  glance-data:
    driver: local 